import type { Reward } from "@/features/economy/types";

export const seedRewards: Reward[] = [
  {
    id: "title_first_rep",
    name: "First Rep",
    description: "A starter title for building the habit.",
    cost: 120,
    type: "title",
    metadata: {
      title: "First Rep",
      source: "shop",
      rarity: "common",
      requiredLevel: "1",
      accent: "#c8832b",
    },
    isActive: true,
  },
  {
    id: "title_steady_pace",
    name: "Steady Pace",
    description: "A calm title for keeping the week moving.",
    cost: 320,
    type: "title",
    metadata: {
      title: "Steady Pace",
      source: "shop",
      rarity: "common",
      requiredLevel: "2",
      accent: "#8f6f4e",
    },
    isActive: true,
  },
  {
    id: "title_streak_keeper",
    name: "Streak Keeper",
    description: "Unlocked by protecting your check-in rhythm.",
    cost: 0,
    type: "title",
    metadata: {
      title: "Streak Keeper",
      source: "achievement",
      rarity: "rare",
      unlockRule: "streak:7",
      accent: "#d47a22",
    },
    isActive: true,
  },
  {
    id: "title_quiet_machine",
    name: "Quiet Machine",
    description: "A higher-tier title for long-term execution.",
    cost: 1250,
    type: "title",
    metadata: {
      title: "Quiet Machine",
      source: "shop",
      rarity: "epic",
      requiredLevel: "6",
      accent: "#5c6f68",
    },
    isActive: true,
  },
  {
    id: "badge_first_workout",
    name: "First Workout",
    description: "Complete your first workout.",
    cost: 0,
    type: "badge",
    metadata: {
      source: "achievement",
      rarity: "common",
      unlockRule: "workouts:1",
      icon: "dumbbell",
      accent: "#c8832b",
    },
    isActive: true,
  },
  {
    id: "badge_seven_day_flame",
    name: "7-Day Flame",
    description: "Reach a 7-day check-in streak.",
    cost: 0,
    type: "badge",
    metadata: {
      source: "achievement",
      rarity: "rare",
      unlockRule: "streak:7",
      icon: "flame",
      accent: "#e06b2d",
    },
    isActive: true,
  },
  {
    id: "badge_life_basics",
    name: "Life Basics",
    description: "Reach a 7-day Life streak.",
    cost: 0,
    type: "badge",
    metadata: {
      source: "achievement",
      rarity: "rare",
      unlockRule: "life:7",
      icon: "sparkle",
      accent: "#4f8b79",
    },
    isActive: true,
  },
  {
    id: "badge_coin_keeper",
    name: "Coin Keeper",
    description: "Earn 500 total coins.",
    cost: 0,
    type: "badge",
    metadata: {
      source: "achievement",
      rarity: "rare",
      unlockRule: "coins:500",
      icon: "coin",
      accent: "#b98529",
    },
    isActive: true,
  },
  {
    id: "badge_level_five",
    name: "Level 5",
    description: "Reach level 5.",
    cost: 0,
    type: "badge",
    metadata: {
      source: "achievement",
      rarity: "epic",
      unlockRule: "level:5",
      icon: "star",
      accent: "#8364b3",
    },
    isActive: true,
  },
  {
    id: "frame_warm_standard",
    name: "Bronze Halo",
    description: "A warm profile glow with a soft bronze edge.",
    cost: 260,
    type: "frame",
    metadata: {
      source: "shop",
      rarity: "common",
      requiredLevel: "2",
      accent: "#d6a55f",
      frameClass: "warm",
    },
    isActive: true,
  },
  {
    id: "frame_deep_focus",
    name: "Zenith Glass",
    description: "A cool glass frame with a quiet premium finish.",
    cost: 760,
    type: "frame",
    metadata: {
      source: "shop",
      rarity: "rare",
      requiredLevel: "4",
      accent: "#51645d",
      frameClass: "focus",
    },
    isActive: true,
  },
  {
    id: "frame_flame_line",
    name: "Ember Line",
    description: "A streak-forged frame with a bright ember gradient.",
    cost: 0,
    type: "frame",
    metadata: {
      source: "achievement",
      rarity: "epic",
      unlockRule: "streak:14",
      accent: "#e06b2d",
      frameClass: "flame",
    },
    isActive: true,
  },
];
