import type { Reward } from "@/features/economy/types";

export const seedRewards: Reward[] = [
  {
    id: "title_first_rep",
    name: "First Rep",
    description: "A starter title for building the habit.",
    cost: 120,
    type: "title",
    metadata: { title: "First Rep" },
    isActive: true,
  },
  {
    id: "title_steady_pace",
    name: "Steady Pace",
    description: "For the user who keeps the week moving.",
    cost: 260,
    type: "title",
    metadata: { title: "Steady Pace" },
    isActive: true,
  },
  {
    id: "title_session_finisher",
    name: "Session Finisher",
    description: "A clean title for closing workouts consistently.",
    cost: 520,
    type: "title",
    metadata: { title: "Session Finisher" },
    isActive: true,
  },
  {
    id: "title_volume_builder",
    name: "Volume Builder",
    description: "For logging enough work to make progress visible.",
    cost: 900,
    type: "title",
    metadata: { title: "Volume Builder" },
    isActive: true,
  },
  {
    id: "title_streak_keeper",
    name: "Streak Keeper",
    description: "A long-term title for protecting the rhythm.",
    cost: 1500,
    type: "title",
    metadata: { title: "Streak Keeper" },
    isActive: true,
  },
  {
    id: "title_cardio_spark",
    name: "Cardio Spark",
    description: "For keeping conditioning in the rotation.",
    cost: 2200,
    type: "title",
    metadata: { title: "Cardio Spark" },
    isActive: true,
  },
  {
    id: "title_life_in_order",
    name: "Life in Order",
    description: "A title for making the small daily things count.",
    cost: 3200,
    type: "title",
    metadata: { title: "Life in Order" },
    isActive: true,
  },
  {
    id: "title_quiet_machine",
    name: "Quiet Machine",
    description: "A premium title for calm, repeated execution.",
    cost: 5000,
    type: "title",
    metadata: { title: "Quiet Machine" },
    isActive: true,
  },
];
