import type { Quest } from "@/features/economy/types";

export const dailyQuests: Quest[] = [
  {
    id: "quest_complete_1_workout",
    code: "complete_1_workout",
    name: "Complete one workout",
    description: "Complete 1 workout today.",
    period: "daily",
    targetType: "workout_completed",
    targetValue: 1,
    coinReward: 30,
    xpReward: 20,
    isActive: true,
  },
  {
    id: "quest_log_3_exercises",
    code: "log_3_exercises",
    name: "Build volume",
    description: "Log 3 exercises in any workout.",
    period: "daily",
    targetType: "exercise_count",
    targetValue: 3,
    coinReward: 40,
    xpReward: 30,
    isActive: true,
  },
  {
    id: "quest_train_legs",
    code: "train_legs",
    name: "Leg day bonus",
    description: "Log any leg exercise.",
    period: "daily",
    targetType: "category_logged",
    targetValue: 1,
    category: "legs",
    coinReward: 25,
    xpReward: 20,
    isActive: true,
  },
  {
    id: "quest_cardio_10",
    code: "cardio_10_minutes",
    name: "Raise your heart rate",
    description: "Log 10 minutes of cardio.",
    period: "daily",
    targetType: "duration_seconds",
    targetValue: 600,
    category: "cardio",
    coinReward: 35,
    xpReward: 25,
    isActive: true,
  },
];
