import type { Quest } from "@/features/economy/types";

export const dailyQuests: Quest[] = [
  {
    id: "quest_complete_1_workout",
    code: "complete_1_workout",
    name: "完成一次訓練",
    description: "今天完成 1 次訓練。",
    period: "daily",
    targetType: "workout_completed",
    targetValue: 1,
    coinReward: 30,
    xpReward: 20,
    isActive: true,
  },
  {
    id: "quest_log_3_exercises",
    code: "log_3_exercises",
    name: "累積訓練量",
    description: "任一訓練中紀錄 3 個動作。",
    period: "daily",
    targetType: "exercise_count",
    targetValue: 3,
    coinReward: 40,
    xpReward: 30,
    isActive: true,
  },
  {
    id: "quest_train_legs",
    code: "train_legs",
    name: "腿日加分",
    description: "紀錄任一腿部動作。",
    period: "daily",
    targetType: "category_logged",
    targetValue: 1,
    category: "legs",
    coinReward: 25,
    xpReward: 20,
    isActive: true,
  },
  {
    id: "quest_cardio_10",
    code: "cardio_10_minutes",
    name: "心率啟動",
    description: "紀錄 10 分鐘有氧。",
    period: "daily",
    targetType: "duration_seconds",
    targetValue: 600,
    category: "cardio",
    coinReward: 35,
    xpReward: 25,
    isActive: true,
  },
];
